apiVersion: v1
kind: Namespace
metadata:
  name: cas
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cas
  labels:
    app: redis
spec:
  ports:
    - name: redis-port
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: cas
data:
  redis-config: |
    maxmemory 1024mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: cas
  labels:
    app: redis
spec:
  containers:
    - image: redis:5
      name: redis
      ports: 
        - containerPort: 6379
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /usr/local/etc/redis
          name: config
  volumes:
    - emptyDir: {}
      name: data
    - configMap:
        items:
          - key: redis-config
            path: redis.conf
        name: redis-config
      name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5
          ports:
            - name: redis-port
              containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /usr/local/etc/redis
              name: config
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
        items:
          - key: redis-config
            path: redis.conf
        name: redis-config
      name: config
---
apiVersion: v1
kind: Service
metadata:
  name: cas
  namespace: cas
  labels:
    app: cas
spec:
  type: NodePort
  selector:
    app: cas
  sessionAffinity: ClientIP
  ports:
  - nodePort: 30080
    port: 8443
    protocol: TCP
    targetPort: 8443
