apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drupal
      tier: frontend
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
    spec:
      initContainers:
        - name: init-site-volume
          image: drupal:7.66
          command: ["/bin/bash", "-c"]
          args:
            ["cp -r /var/www/html /data/; chown www-data:www-data /data/ -R"]
          volumeMounts:
            - mountPath: /data
              name: drupal
      containers:
        - image: drupal:7.66
          name: drupal
          ports:
            - containerPort: 80
              name: drupal
          volumeMounts:
            - name: drupal
              mountPath: /var/www/html
              subPath: html
      volumes:
        - name: drupal
          persistentVolumeClaim:
            claimName: drupal-pvc
