apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-blackbox-exporter
  namespace: kube-log
  labels:
    app: prometheus-blackbox-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-blackbox-exporter
    spec:
      restartPolicy: Always
      containers:
        - name: prometheus-blackbox-exporter
          image: prom/blackbox-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: transport
              containerPort: 9115
          readinessProbe:
            tcpSocket:
              port: 9115
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 60Mi
              cpu: 200m
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox_exporter
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-conf
